# Generated by Django 5.1.3 on 2024-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_student_disciplines"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
