# Generated by Django 5.1.3 on 2024-12-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_game_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="file_path",
            field=models.CharField(default="NonePath", max_length=255),
        ),
        migrations.AlterField(
            model_name="game",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="core.discipline",
            ),
        ),
    ]
